### ISSUE TITLE
Empty Quantity blocks, expr→value for units, and alcohol_servings slot refs (5 cohorts, 18 errors)

### ISSUE THREAD

**Issue by amc-corey-cox** [RTIInternational/NHLBI-BDC-DMC-HV#444]
Errors found during downstream BDC pipeline testing of 2026.03-2-rc2 release. 18 total across 5 cohorts; CHS, MESA, HCHS/SOL, and FHS are clean.

## 1. Empty Quantity slot_derivations after commenting out conversions (10 errors)

`AttributeError: 'NoneType' object has no attribute 'items'` — nested Quantity blocks have `slot_derivations: None` after broken unit conversions were commented out in PR #436. The empty Quantity shell was left behind.

**Fix:** Comment out or remove the entire `object_derivations` / `Quantity` block, not just the slot_derivations contents.

| Cohort | File | Errors |
|--------|------|--------|
| ARIC | insulin_blood.yaml | 1 |
| ARIC | factor_8.yaml | 1 |
| CARDIA | insulin_blood.yaml | 3 |
| JHS | insulin_blood.yaml | 2 |
| WHI | insulin_blood.yaml | 2 |
| | **Subtotal** | **9** |

## 2. COPDGene: expr→value for unit fields (2 errors)

Same class of issue as #434. `expr: 'mm[Hg]'` is parsed as Python syntax due to the brackets. Should be `value: 'mm[Hg]'`.

| File | Errors |
|------|--------|
| bp_diastolic.yaml | 1 |
| bp_systolic.yaml | 1 |

## 3. CARDIA: alcohol_servings.yaml wrong slot reference (7 errors)

`ValueError: No such slot value_decimal` across 7 different pht tables. The slot `value_decimal` doesn't exist in the referenced source tables.
